version: '3.9'
services:
  api:
    build: ./api
    image: ynov/api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
      - MONGO_URI=${MONGO_URI}

  bot:
    build: ./bot
    image: ynov/bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PORT=${BOT_PORT}

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:${API_PORT}
    image: ynov/frontend
    ports:
      - ${FRONTEND_PORT}:80

  db:
    image: mongo
