version: '3.9'
services:
  api:
    build:
      context: ./api
      args:
        - PORT=${API_PORT}
    image: ynov/api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
      - MONGO_URI=mongodb://db

  bot:
    build:
      context: ./bot
      args:
        - PORT=${BOT_PORT}
    image: ynov/bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PORT=${BOT_PORT}
      - GUILD_ID=${GUILD_ID}
      - API_URL=http://api:${API_PORT}

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${API_URL}:${API_PORT}
    image: ynov/frontend
    ports:
      - ${FRONTEND_PORT}:80

  db:
    image: mongo

# Pas besoins de healthcheck car inutile ici,
# le compose sert pour le développement local, de toute façon ils sont dans les dockerfile et docker les prends meme en compose.
# kubernetes le gérera pour la prod.
