name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the API Docker image
      run: docker build ./api --tag gpatarin/api:latest
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push API Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
  build-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the API Docker image
      run: docker build ./api --tag gpatarin/bot:latest
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push API Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./bot
        file: ./bot/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bot:latest
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the API Docker image
      run: docker build ./api --tag gpatarin/frontend:latest
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push API Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
